# Generated by Django 6.0.1 on 2026-01-13 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='registrations.registration'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_status'], name='donations_d_payment_453297_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['created_at'], name='donations_d_created_26bd74_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_id__isnull', False), models.Q(('transaction_id', ''), _negated=True)), fields=('transaction_id', 'payment_provider'), name='unique_transaction_id_per_provider'),
        ),
    ]
